export const VALIDATION_SCHEMA = {
  email: { regex: /\bemail\b/i, decorator: "IsEmail" },
  required: { regex: /\brequired\b/i, decorator: "IsNotEmpty" },
  minLength: { regex: /\bminLength\s*\(\s*(\d+)\s*\)\b/i, decorator: "MinLength" },
  maxLength: { regex: /\bmaxLength\s*\(\s*(\d+)\s*\)\b/i, decorator: "MaxLength" },
  min: { regex: /\bmin\s*\(\s*(\d+)\s*\)\b/i, decorator: "Min" },
  max: { regex: /\bmax\s*\(\s*(\d+)\s*\)\b/i, decorator: "Max" },
  pattern: { regex: /\bpattern\s*\(\s*([^)]+)\s*\)\b/i, decorator: "Matches" },
  isDate: { regex: /\bdate\b/i, decorator: "IsDate" },
  isUrl: { regex: /\burl\b/i, decorator: "IsUrl" },
  isUUID: { regex: /\bUUID\b/i, decorator: "IsUUID" },
  isEnum: { regex: /\benum\s*\(\s*([^)]+)\s*\)\b/i, decorator: "IsEnum" },
  isArray: { regex: /\barray\b/i, decorator: "IsArray" },
  arrayMinSize: {
    regex: /\barrayMinSize\s*\(\s*(\d+)\s*\)\b/i,
    decorator: "ArrayMinSize",
  },
  arrayMaxSize: {
    regex: /\barrayMaxSize\s*\(\s*(\d+)\s*\)\b/i,
    decorator: "ArrayMaxSize",
  },
  equals: { regex: /\bequals\s*\(\s*([^)]+)\s*\)\b/i, decorator: "Equals" },
  isBoolean: { regex: /\bboolean\b/i, decorator: "IsBoolean" },
  isNumber: { regex: /\bnumber\b/i, decorator: "IsNumber" },
  isInt: { regex: /\binteger\b/i, decorator: "IsInt" },
  isString: { regex: /\bstring\b/i, decorator: "IsString" },
  isDateString: { regex: /\bdatestring\b/i, decorator: "IsDateString" },
  isHexColor: { regex: /\bhexcolor\b/i, decorator: "IsHexColor" },
  isLatitude: { regex: /\blatitude\b/i, decorator: "IsLatitude" },
  isLongitude: { regex: /\blongitude\b/i, decorator: "IsLongitude" },
};
