export const VALIDATION_ANNOTATION_REGEXES = {
  email: /@email/i,
  required: /@required/i,
  minLength: /@minLength\s*\(\s*(\d+)\s*\)/i,
  maxLength: /@maxLength\s*\(\s*(\d+)\s*\)/i,
  min: /@min\s*\(\s*(\d+)\s*\)/i,
  max: /@max\s*\(\s*(\d+)\s*\)/i,
  pattern: /@pattern\s*\(\s*([^)]+)\s*\)/i,
  isDate: /@isDate/i,
  isUrl: /@isUrl/i,
  isUUID: /@isUUID/i,
  isEnum: /@isEnum\s*\(\s*([^)]+)\s*\)/i,
  isArray: /@isArray/i,
  arrayMinSize: /@arrayMinSize\s*\(\s*(\d+)\s*\)/i,
  arrayMaxSize: /@arrayMaxSize\s*\(\s*(\d+)\s*\)/i,
  equals: /@equals\s*\(\s*([^)]+)\s*\)/i,
  isBoolean: /@isBoolean/i,
  isNumber: /@isNumber/i,
  isInt: /@isInt/i,
  isString: /@isString/i,
};
